{name: 'John Boehner', state_id: 'OH', current_position: 'US House of Representatives', descent: 'Boehner is of German descent', description: '', twitter: 'SpeakerBoehner'},
    {name: 'Ted Cruz', state_id: 'FL', current_position: 'US House of Representatives', descent: 'Cruz was born in Canada and immigrated to USA in _____', description: '', twitter: 'tedcruz'},
    {name: 'Michelle Bachmann', state_id: 'MN', current_position: 'US House of Representatives', descent: 'Bachmann is of Norweigan descent', description: '', twitter: 'michelebachmann'},
    {name: 'Mark Krikorian', state_id: 'DC', current_position: 'Executive director of the Center for Immigration Studies, a think-tank in Maryland that promotes stricter immigration control and enforcement', descent: 'Krikorian was born in Armenia and immigrated to USA in ____', description: '', twitter: 'markskrikorian'},
    {name: 'Susana Martinez', state_id: 'NM', current_position: 'Governor of New Mexico', descent: 'Martinez\'s grandparents immigrated from Mexico', description: '', twitter: 'gov_martinez'},
    {name: 'George Borjas', state_id: 'MA', current_position: 'Professor of Economics and Social Policy at the Harvard Kennedy School', descent: 'Borjas was born in Cuba and immigrated to USA ', description: '', twitter: 'kennedy_school'},
    {name: 'Joe Arpaio', state_id: 'AZ', current_position: 'Sheriff of Maricopa County, Arizona', descent: 'Arpaio\'s parents emigrated from Italy', description: 'Arpaio has repeatedly racially targeted Latinos with years of abuses conducted under the shelter of Arizona\'s immigration law, including illegal stops, searches and arrests that provoked widespread fear among citizens.', twitter: 'realsheriffjoe'},
    {name: 'Buck McKeon', state_id: 'CA', current_position: 'Former U.S House of Representatives; Businessman', descent: 'Irish Descent', description: 'There are people that can’t tell the difference between a Hispanic person and an Arab person. They can mingle in, and they can get in here, and then they can do damage', twitter: 'mckeon4congress'},
    {name: 'Peter Brimelow', state_id: 'CT', current_position: 'Writer', descent: 'Brimelow was born in England and immigrated to USA in ____', description: '', twitter: ''},
    {name: 'Phyllis Schafly', state_id: 'MO', current_position: 'Activist', descent: 'Great-Grandfather immigrated from England', description: '', twitter: 'phyllisschlafly'},
    {name: 'Tom Tancredo', state_id: 'CO', current_position: 'Formerly in US House of Representatives, Colorado Gubernatorial Candidate 2014', descent: 'All 4 grandparents immigrated from Italy', description: '', twitter: 'ttancredo'},
    {name: 'John Tanton', state_id: 'MI', current_position: 'Retired Doctor; Environmental Activist', descent: 'Father immigrated from Canada and Grandfather immigrated from Germany', description: '', twitter: ''},
    {name: 'Bobby Jindal', state_id: 'LA', current_position: 'Governor of Louisiana', descent: 'Parents immigrated from India', description: '', twitter: 'bobbyjindal'},
    {name: 'Virginia Abernethy', state_id: 'TN', current_position: 'Professor Emerita at Vanderbilt University best known for work on population demography and for being a white separatist', descent: 'Abernathy was born in Cuba and immigrated to USA in ____', description: '', twitter: ''},
    {name: 'Steven Palazzo', state_id: 'MS', current_position: 'US House of Representatives', descent: 'Palazzo is of Italian descent', description: '', twitter: 'congpalazzo'},
    {name: 'Lou Barletta', state_id: 'PA', current_position: 'US House of Representatives', descent: 'Barletta is of Italian descent', description: '', twitter: 'reploubarletta'},
    {name: 'Jeff Sessions ', state_id: 'AL', current_position: 'US Senate', descent: 'Sessions is of English, Scottish, and Irish descent', description: '', twitter: 'senatorsessions'},
    {name: 'Rick Santelli', state_id: 'IL', current_position: 'CNBC Commentator', descent: 'Santelli is of Italian descent', description: '', twitter: 'ricksantelli'},
    {name: 'Brian Sandoval', state_id: 'NV', current_position: 'Governor of Nevada', descent: 'Sandoval is of Mexican descent', description: '', twitter: 'briansandoval'},
    {name: 'Lisa Murkowski', state_id: 'AK', current_position: 'US Senate', descent: 'Murkowski is of Polish, Irish, and French Canadian descent', description: '', twitter: 'lisamurkowski'},
    {name: 'John Thune', state_id: 'SD', current_position: 'US Senate', descent: '', description: '', twitter: 'senjohnthune'},
    {name: '', state_id: 'ND', current_position: '', descent: '', description: '', twitter: ''},
    {name: 'Sam Brownback ', state_id: 'KS', current_position: 'Governor of Kansas', descent: 'Brownback is of German descent', description: '', twitter: 'govsambrownback'},
    {name: 'John Barrasso ', state_id: 'WY', current_position: 'US Senate', descent: '', description: '', twitter: ''},
    {name: 'Peter King', state_id: 'NY', current_position: 'US House of Representatives', descent: 'King is of Irish and Welsh descent', description: '', twitter: 'reppeteking'},
    {name: 'Virginia Foxx (palmeri)', state_id: 'NC', current_position: 'Congresswoman - US House of Representatives ', descent: 'Granddaughter of Italian immigrants', description: '', twitter: 'virginiafoxx'},
    {name: 'Bob Goodlatte', state_id: 'VA', current_position: 'US House of Representatives', descent: 'Maternal Grandfather from Latvia', description: ' "You\'re going to have to have a program that assures those farms and those processing plants that there will be workers," Representative Goodlate says. "Because if you give them [undocumented workers] legal status, they can work anywhere in the United States — they\'re not going to necessarily work at the hardest, toughest, dirtiest jobs."', twitter: 'repgoodlatte'},
    {name: 'Michael Burgess', state_id: 'TX', current_position: 'US House of Representatives', descent: 'Paternal family from Nova Scotia', description: '', twitter: 'michaelcburgess'},
    {name: '', state_id: 'GA', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'IN', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'AR', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'RI', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'SC', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'HI', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'WA', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'OR', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'ID', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'MT', current_position: '', descent: 'D', description: '', twitter: ''},
    {name: '', state_id: 'KY', current_position: '', descent: '', description: '', twitter: ''},
    {name: 'Mark Krikorian', state_id: 'MD', current_position: 'Executive director of the Center for Immigration Studies, a think-tank that promotes stricter immigration control and enforcement', descent: 'Krikorian was born in Armenia and immigrated to USA in ____', description: '', twitter: ''},
    {name: '', state_id: 'DE', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'NJ', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'OK', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'NE', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'UT', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'WV', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'ME', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'VT', current_position: '', descent: '', description: '', twitter: ''},
    {name: '', state_id: 'NH', current_position: '', descent: '', description: '', twitter: ''},
    {name: 'Ron Johnson', state_id: 'WI', current_position: 'Senator', descent: 'His father was of Norwegian descent and his mother was of German ancestry', description: '“They were coming across the border and they wanted to be apprehended so that we would detain them for a couple days, a couple weeks and they would get in the adjudication process and then they would be dispersed around America, knowing full well they would be able to stay.', twitter: ''},
    {name: 'Steven King', state_id: 'IA', current_position: 'US House of Representatives', descent: '', description: '', twitter: ''},
    {name: 'Steve Scalise', state_id: '', current_position: 'US House Majority Whip', descent: 'Italy', description: '', twitter: ''},
    {name: 'Dana Rohrabacher', state_id: '', current_position: 'US House', descent: 'Germany', description: '', twitter: ''},
    {name: 'Michelle Malkin', state_id: '', current_position: 'Blogger, Commentator, Fox News', descent: 'Phillipines', description: '', twitter: ''},
    {name: 'Marco Rubio', state_id: '', current_position: 'US Senate', descent: 'Cuba', description: '', twitter: ''},
    {name: 'Gus Bilirakis', state_id: '', current_position: 'US House', descent: 'Greece', description: '', twitter: ''},
    {name: 'Pat Buchanan', state_id: '', current_position: 'Conservative Commentator', descent: 'Germany', description: '', twitter: ''},
    {name: 'Darrell Issa', state_id: 'CA', current_position: 'US House of Representatives', descent: 'Grandparents immigrated from Lebanon', description: '', twitter: ''},
    {name: 'Michael Hart ', state_id: '', current_position: '', descent: '', description: '', twitter: ''},
    {name: 'tom mcclintock', state_id: 'CA', current_position: '', descent: 'Scotland, UK', description: '', twitter: ''},
    {name: 'Judge Andrew Hanen of the U.S. District Court in Brownsville, Texas', state_id: '', current_position: '', descent: '', description: '', twitter: ''}